server:
  port: 8081
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://purgae.net:3306/purgae?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.username}
    password: ${db.pw}

  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://db:3306/colors?serverTimezone=UTC&characterEncoding=UTF-8
  #    username: root
  #    password: root

  data:
    web:
      pageable:
        default-page-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    generate-ddl: true
logging:
  level:
    org.hibernate:
      type:
        descriptor:
          sql: trace
      SQL: debug
